"""
Data Models

Generated by QuantumLayer Factory
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime
import uuid

class User(BaseModel):
    id: str
    email: str
    name: str
    password_hash: str
    created_at: datetime
    updated_at: datetime

