apiVersion: v1
kind: Secret
metadata:
  name: qlf-secrets
  namespace: quantumlayer-factory
type: Opaque
stringData:
  # Database Configuration
  POSTGRES_USER: "qlfadmin"
  POSTGRES_PASSWORD: "YOUR_POSTGRES_PASSWORD" # Replace with actual password
  POSTGRES_HOST: "qlf-prod-postgres.postgres.database.azure.com"
  POSTGRES_DB: "quantumlayer"
  POSTGRES_PORT: "5432"
  DATABASE_URL: "postgresql://qlfadmin:YOUR_POSTGRES_PASSWORD@qlf-prod-postgres.postgres.database.azure.com:5432/quantumlayer?sslmode=require"

  # Temporal Database Configuration
  TEMPORAL_POSTGRES_DB: "temporal"
  TEMPORAL_DATABASE_URL: "postgresql://qlfadmin:YOUR_POSTGRES_PASSWORD@qlf-prod-postgres.postgres.database.azure.com:5432/temporal?sslmode=require"

  # Redis Configuration
  REDIS_URL: "rediss://qlf-prod-redis.redis.cache.windows.net:6380"
  REDIS_PASSWORD: "YOUR_REDIS_PASSWORD" # Replace with actual password

  # Azure OpenAI Configuration
  AZURE_OPENAI_ENDPOINT: "https://myazurellm.openai.azure.com/"
  AZURE_OPENAI_API_KEY: "YOUR_AZURE_OPENAI_KEY" # Replace with actual key
  AZURE_OPENAI_DEPLOYMENT: "gpt-4-turbo"
  AZURE_OPENAI_API_VERSION: "2024-02-01"

  # AWS Bedrock Configuration (Optional)
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY" # Replace with actual key
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_KEY" # Replace with actual secret
  AWS_REGION: "eu-west-2"

  # Application Configuration
  QLF_LLM_PROVIDER: "azure"
  QLF_LLM_MODEL: "gpt-4"
  JWT_SECRET_KEY: "YOUR_JWT_SECRET" # Replace with a secure random string

  # Temporal Configuration
  TEMPORAL_ADDRESS: "temporal-frontend:7233"
  TEMPORAL_NAMESPACE: "default"

  # MinIO/Storage Configuration
  MINIO_ENDPOINT: "minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
---
apiVersion: v1
kind: Secret
metadata:
  name: qlf-tls
  namespace: quantumlayer-factory
type: kubernetes.io/tls
data:
  # Generate with: kubectl create secret tls qlf-tls --cert=path/to/cert.crt --key=path/to/cert.key --dry-run=client -o yaml
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t # Base64 encoded private key